modLoader="javafml"
loaderVersion="[49,)"
license="All rights reserved"
logoFile="ruthumb.png"
displayURL="https://discord.gg/Ss8UHPqHPj"

[[mods]]
modId="regions_unexplored"
version="0.5.4"
displayName="Regions Unexplored"
authors="UHQ_GAMES"
description='''
Regions Unexplored is a mod that aims to add new content to the overworld. Currently adds over 70 new biomes!
'''

[[dependencies.regions_unexplored]]
modId="forge"
mandatory=true
versionRange="[49.0.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.regions_unexplored]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.regions_unexplored]]
modId="terrablender"
mandatory=true
versionRange="[3.3.0.9,)"
ordering="NONE"
side="BOTH"
